### ISSUE TITLE
Some programs have "PID: 0"; suspending them freezes desktop

### ISSUE THREAD

**Issue by michaelneverwins** [Merrit/nyrna#104]
Running Nyrna v2.6.0 on Linux Mint 20.3, the Steam window shows up as N/A with PID 0. (Note that this is the version of Steam provided by Mint's package manager, not the Flatpak version.) Additionally, while some Steam games (such as the Linux version of [*Dusk*](https://store.steampowered.com/app/519860/DUSK/) and the Windows version of [*Alan Wake*](https://store.steampowered.com/app/108710/Alan_Wake/) under Proton 7.0) do show non-zero PIDs and can be suspended by Nyrna, some others (such as the Linux version of [*Detention*](https://store.steampowered.com/app/555220/Detention/)) are identified as PID 0 as well.

![nyrna-pid-0](https://user-images.githubusercontent.com/73746653/199375186-ec8e416d-8924-4cbc-b589-5e615a7be115.png)

I should have guessed that suspending *Detention* wouldn't work, but I tried anyway and it froze my desktop. I avoided a hard reset by logging out with Ctrl+Alt+Backspace, but of course that closed all of my programs. The same happens if I try to suspend Steam itself (via the N/A entry).

Based on the comments in #13, I realize that programs may show up as PID 0 due to issues that cannot be fixed on Nyrna's end. However, if trying to suspend such processes is likely to cause problems, then I would say they shouldn't be clickable. Maybe the specific desktop-freezing issue I'm experiencing when I click a PID 0 entry is a quirk of Linux Mint or Cinnamon, and maybe the result would be different on another Linux distro or desktop environment, but at best I assume it would do nothing — that is, I assume Nyrna can't actually suspend a program if it erroneously believes the PID is 0. If my assumption is right, then making PID 0 entries unclickable (or not displaying them at all) is probably a good idea.

**Comment by michaelneverwins** [comment]
I tested the attached Nyrna build with the same set of games.
* As before, it detected *Dusk* and *Alan Wake*, and I was able to suspend both of them.
* Steam and *Detention*, which were shown with "PID: 0" before, are no longer listed.

![nyrna-no-pid-0](https://user-images.githubusercontent.com/73746653/199637645-0d37ebed-32e4-4b6e-bf2f-9098132247c7.png)

So I think this addresses my concern about freezing up my system by accidentally clicking one of those "PID: 0" entries again.

**Comment by michaelneverwins** [comment]
As a side note, I can't seem to get the PID of the *Detention* window by playing around with `wmctrl` and `xdotool` either — which is not really surprising, because I'm pretty sure these are Nyrna dependencies. Running `wmctrl -lp` shows PID 0 for *Detention*, and if I pass the *Detention* window ID printed by `wmctrl -lp` as an argument to `xdotool getwindowpid` then it tells me the window has no PID associated with it, so I'm guessing I've just manually run into the same roadblock as Nyrna.

**Comment by Merrit** [comment]
Yes, probably the same issue. If you can reproduce this on a free game (or one I have lol) I can take a look to see if there is anything else that can be done to find the pid for it.

You can also try finding the pid by running in terminal `xprop | awk '/PID/ {print $3}'` and clicking on the window.
