### ISSUE TITLE
[Feature] Suspend all windows of one appliction in one click

### ISSUE THREAD

**Issue by UlyssesZh** [Merrit/nyrna#107]
It will be helpful if there are a lot of instances of the same application.

**Comment by Merrit** [comment]
I am not sure how this would work from a UI & UX perspective. Do you have suggestions or a mockup?

**Comment by Merrit** [comment]
Yes a context menu would probably work well. :+1:

**Comment by Merrit** [comment]
This is available as of https://github.com/Merrit/nyrna/releases/tag/v2.10.0 :grinning:
