### ISSUE TITLE
Error resuming Slack on Linux

### ISSUE THREAD

**Issue by UlyssesZh** [Merrit/nyrna#108]
I am using Ubuntu 20.04. Nyrna can suspend Slack, but it pops up a window saying that there is an error when I try to resume it. Screenshot:
![image](https://user-images.githubusercontent.com/26196187/202022572-a9ca94b7-b09c-4556-8a59-588d7ce2b29f.png)

**Comment by Merrit** [comment]
Works as expected for me on Fedora. Can you try running Nyrna from the terminal, see if there is any helpful output in the console?

**Comment by UlyssesZh** [comment]
I found that I can only reproduce this if I suspend (sleep) my computer after suspending Slack.
The error in terminal:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      State.setState (package:flutter/src/widgets/framework.dart:1134)
#1      _WindowTileState.build.<anonymous closure> (package:nyrna/apps_list/widgets/window_tile.dart:67)
<asynchronous suspension>
```

**Comment by Merrit** [comment]
I don't immediately see what could be causing that.. can you try restarting Nyrna after you resume your computer, see if it works then?

**Comment by UlyssesZh** [comment]
No, it doesn't.

**Comment by Merrit** [comment]
I am unable to reproduce this locally - I suspended slack, suspended my computer; then after resuming my computer Nyrna resumed slack as expected.

It may be an issue specific to Ubuntu 20.04. I can't test that unfortunately as my laptop died and I don't have a spare computer to load a different distro.

**Comment by Merrit** [comment]
@UlyssesZh I've made a change that may resolve the error you saw in the terminal. Probably will not affect the original issue, but might at least help get closer to the actual problem.

Please try this version and see if there is any change / if it shows that error in terminal.

[Nyrna-Linux-Portable.tar.gz](https://github.com/Merrit/nyrna/files/10069036/Nyrna-Linux-Portable.tar.gz)

**Comment by Merrit** [comment]
Additionally the release of v2.8.0 provides more detailed process info, a better error message, and detailed logging by launching with the verbose flag: `--verbose`

If this is still an issue please check again with the new version and feel free to reopen the issue.
