### ISSUE TITLE
Punch Planet sometimes displays an error but resumes successfully

### ISSUE THREAD

**Issue by henrebotha** [Merrit/nyrna#110]
I'm on Xubuntu 22.04, running Punch Planet (using Proton) through Steam. Suspending & resuming Punch Planet _usually_ works fine. Occasionally, though, I get this error.

![image](https://user-images.githubusercontent.com/5593874/203839908-1cf432ee-b749-48da-9acf-911fa5b9209b.png)

Note that it doesn't actually name Punch Planet in the error message. To my knowledge, also, Punch Planet does not use Easy Anti-Cheat.

**Comment by Merrit** [comment]
Hey @henrebotha :wave:

Thanks for the issue! This doesn't seem ideal.. I will have a think on how I can improve the error message, maybe surface helpful information..

To confirm, when you get this error the suspend/resume still works properly?

**Comment by henrebotha** [comment]
Yep, it still resumes properly. There's a notable minor difference in behaviour: Normally, when I resume the game, it instantly takes focus; but when this error happens, the game is resumed without taking focus (and therefore it's not immediately super obvious that it did successfully resume).

**Comment by Merrit** [comment]
Alright that is also helpful information. I will investigate more when I get a chance. :+1:

**Comment by Merrit** [comment]
With the [latest release](https://github.com/Merrit/nyrna/releases/tag/v2.8.0) this will hopefully either

1. No longer happen
or
2. Provide a better error

**Comment by Merrit** [comment]
Closing this, if it still seems to be an issue feel free to reopen! :)
