### ISSUE TITLE
High VRAM usage

### ISSUE THREAD

**Issue by albin-engstrom** [Merrit/nyrna#111]
The UI has what seems to me to be an excessively high VRAM usage.
It quickly climbs to around the 800-900MiB range.
Which falls just short of what Xorg uses, as well as being a bit lower than what Firefox uses.

It does not seem to climb further, and while it's not a wildly unreasonable amount of VRAM it is notably more than I'd expect it to use. So I'm not sure whether this is as intended or a bug.

This is on Arch and I normally use Nyrna installed through the AUR, but as that is not an officially supported way of using it I also tried the most recent AppImage and the portable download, and both had the same behaviour.

**Comment by Merrit** [comment]
Hey @albin-engstrom :wave: 

Thanks for opening the issue! That definitely seems odd. How are you monitoring the GPU RAM usage?

**Comment by albin-engstrom** [comment]
Hello, the tool I'm using is nvidia-smi.

I always monitor total GPU memory usage, but this I only run once in a while when I want to check more specific things.
So I can't say for how long this has been the case without me noticing.

Another thing I noticed today is that if I minimize Nyrna and don't use it for a while, VRAM usage drops significantly, I saw it only using 30MiB once. But then, even if I still don't interact with it, usage start to climb up to these high levels again.
Then it drops once again, and it seemingly repeats indefinitely.

And during these low usage periods, if I interact with it, even if only moving my mouse over it, usage imidiately goes high again.

This is my current output of nvidia-smi, with Nyrna recently being started.
I think 855MiB is the highest I've ever seen it use.

![smi](https://user-images.githubusercontent.com/9036709/205265438-fd39a6cd-dfd5-4469-8fa2-ad9a276a7ef8.png)

**Comment by Merrit** [comment]
Please try this dev build and see if there is any difference:

[Nyrna-Linux-Portable.tar.gz](https://github.com/Merrit/nyrna/files/10141732/Nyrna-Linux-Portable.tar.gz)

**Comment by albin-engstrom** [comment]
It seems to have the same behaviour, 859MiB right now and occasionally dropping lower temporarily.

**Comment by Merrit** [comment]
That's odd. I've been monitoring it on my system (Fedora) and it tops out around ~45MB - never anything huge like what you are seeing.

Wondering now if it is a bug with an arch package, might resolve with a system update.. have you only noticed this issue recently?

**Comment by albin-engstrom** [comment]
It might be something else that's bugged, indeed.

I've only noticed this recently, but I don't check individual processes VRAM usage like this very regularly, so it's possible it's been like this for a long time. Although, of course, conversely it could have started just a few days ago as well.

**Comment by Merrit** [comment]
@albin-engstrom Are you still seeing this with the [latest release](https://github.com/Merrit/nyrna/releases/tag/v2.8.0) / after updating your system?

**Comment by albin-engstrom** [comment]
Unfortunately the issue remains.

With 2.8.0 and a system that's up to date as of a few hours ago.

**Comment by Merrit** [comment]
From the tools you monitor with I presume you have an nvidia gpu..

Makes me wonder, which driver are you using, nouveau or nvidia? Their performance on Linux is known to be fairly iffy.. I have an old PC that is using the nouveau driver, but there doesn't seem any way to monitor the vram usage with nouveau.

It may just come down to being yet another an issue with nvidia. :/

**Comment by albin-engstrom** [comment]
Yeah, I'm using an Nvidia GPU and the proprietary drivers.
It might indeed be an issue with those, although I've only noticed the issue with Nyrna.

Other things seem to use about the amount of VRAM I'd expect, games and Blender use more but that is expected.

It also does not seem to be a leak, as the VRAM usage of Nyrna is high but remarkably consistent.

**Comment by Merrit** [comment]
Also possible that it is an issue where the nvidia driver is reporting the value for Nyrna incorrectly for some reason. Hard to be sure within the constraints..

Perhaps checking with a different monitoring tool like `nvtop` might report something different, though I doubt it.

At this point I am not sure of how to investigate further. 😕

**Comment by albin-engstrom** [comment]
Nvtop reports the same numbers, and MangoHud which only reports total usage shows consistent totals when opening/closing Nyrna.

Yeah, I understand it's tricky to investigate. Especially when we don't know how to reproduce it.

The positive side of it is that it's not a huge issue for me, more of a slight inconvenience.
I mainly use the hotkey and toggle functionality, so I largely don't need to have the UI running.

So I'm fine with simply waiting and seeing if something changes eventually.
Maybe a system update fixes it, maybe someone else comes along with the same issue and more info, or maybe one of us has an idea.

So I appreciate your effort, but I'm okay with letting this be for a while and seeing what happens.

**Comment by Merrit** [comment]
Alright, I will keep this in mind - like you say, maybe one of us will have an idea of how to investigate further. :slightly_smiling_face:

**Comment by Merrit** [comment]
With the latest version of Nyrna there has been a huge amount of upgrades to the SDK, dependencies, and code cleanup. Worth a look to see if it has resolved your issue. :rainbow:

**Comment by albin-engstrom** [comment]
Thanks for the heads-up, unfortunately the issue remains.

**Comment by albin-engstrom** [comment]
I have been using Nyrna through the hotkey functionality and have been periodically (every couple of months or so) tested the GUI to see if the issue remains.

And I can now happily report that the issue is gone, VRAM usage seems to be stable and under 50MiB.

As I tested so rarely I don't know if it was a graphics driver update, an update to Nyrna itself, or something else that fixed it. 

But either way the it's fixed now, hooray!

**Comment by Merrit** [comment]
That's great to hear! Never had other reports of the issue, nevertheless it irked me :grin: 

Thank you for following up and letting me know~ :blue_heart:
