### ISSUE TITLE
Punch Planet crashes upon resuming (after system sleep)

### ISSUE THREAD

**Issue by henrebotha** [Merrit/nyrna#115]
I came back to my machine after it had slept and tried to resume Punch Planet (I have done this successfully many times). The game appeared for a fraction of a second, then quit entirely.

The logs have almost nothing in them, even when selecting log level `ALL`. I would have expected to see some kind of logging here outside of just the Nyrna app itself.

```
2022-11-22 12:23:14.816928 
INFO 
Logger: LoadingScreen 
Loading screen initializing 
```

i7-8650U, Xubuntu 22.04, Nyrna 2.4.1.

**Comment by Merrit** [comment]
A crash or odd behaviour is definitely a possibility whenever manipulating a process externally the way we are here.

I don't think there is anything Nyrna can do to mitigate this, likely just caught the game at a particularly bad time (caching, saving, loading to/from memory, etc..).

The fact that this has _normally_ worked as expected kind of reaffirms this thought for me.. though if you have any thoughts or suggestions on the matter I am happy to hear! :grinning: 

Nyrna definitely needs more thorough logs, which is something I am working on right now. :)

**Comment by henrebotha** [comment]
I have nothing haha. I think logging is the missing piece of the puzzle here — if we can get some kind of information out to the user about why something crashed, it would be helpful both to users and to you as the maintainer.

> likely just caught the game at a particularly bad time (caching, saving, loading to/from memory, etc..).

I wonder if this can be mitigated. Do operating systems allow us to see, for example, when a process is doing something that's likely to cause issues when suspending/resuming? If we can detect those cases, we could defer suspension until it's safe to suspend. Would of course need a _lot_ of careful thought about the UX, and probably app-specific settings to override such behaviour. Just thinking out loud, really.

**Comment by Merrit** [comment]
> I wonder if this can be mitigated. Do operating systems allow us to see, for example, when a process is doing something that's likely to cause issues when suspending/resuming?

It is my understanding that in general, affecting a process other than that owned by the current application comes with the warning along the lines of "not supported, don't be surprised if this goes badly". We could always check if the process is using a lot of CPU, doing disk I/O, that sort of thing.. but I expect that would prevent Nyrna suspending a whole lot of things (especially games that tend to _always_ be doing a bunch of things).

> if we can get some kind of information out to the user about why something crashed, it would be helpful

Might be doable - attempt interaction, if it fails the error report can contain information like:

- is it still running?
- suspended / normal?
- if not running, did it dump a log in a predictable system location that can be referred to via PID?

Still not 100% sure on how the UX for this would go, but I am currently working on some code cleanup, adding better logging, and then improving this messaging for errors.

**Comment by Merrit** [comment]
There is a [new release](https://github.com/Merrit/nyrna/releases/tag/v2.8.0) which includes:

- Detailed information (arrow on the right hand side of each tile)
- Improved error message
- Many more verbose logs when running with the verbose flag `--verbose`

It may even prevent the crash you experienced thanks to the addition of a [base-level exception catch](https://github.com/Merrit/nyrna/blob/d67fc4ba6b6da6c843b90c9ea0c46923d13b6391/lib/main.dart#L43-L46).

Hopefully this helps! :blue_heart:

**Comment by Merrit** [comment]
Closing this, if it still seems to be an issue feel free to reopen! :)
