### ISSUE TITLE
No Icon in system tray

### ISSUE THREAD

**Issue by Gladox114** [Merrit/nyrna#12]
After executing it, nothing happens except the system monitor saying it's running. Executing it twice gives a notification error that the pause key is already bind so this means everything is good and running but I have no access to change the hotkey because I am using gnome and there is nothing like a system tray icon or gnome extension. 

I can't test the pause function because I am using a laptop that doesn't have this button and I can't change the hotkeys because there is no menu or etc I can access.

OS: Pop!_OS 20.04 (Gnome3.36.3)

**Comment by Merrit** [comment]
![image](https://user-images.githubusercontent.com/9575627/89551916-8061f580-d7d9-11ea-90b7-5338b52c9c04.png)

Did you install `libappindicator3` ?
Since Pop is Ubuntu-based it should be `sudo apt install libappindicator3-1`

This package is required for gnome to show tray icons.

**Comment by Gladox114** [comment]
Well, after reinstalling Linux and trying it again it shows an tray icon. I tried to install libapindicator3 before downloading nyma but it was installed. Also I reinstall Linux because of some other relevant issue.

**Comment by Merrit** [comment]
Alright, well glad everything is working for you :smiley:
