### ISSUE TITLE
Flatpak bug

### ISSUE THREAD

**Issue by Wjxfi** [Merrit/nyrna#158]
When I open it it says that I could not find xdotool and wmctrl (I do not remember exactly what it says)

**Comment by Merrit** [comment]
The error message is:

> Dependency check failed.
> Install the dependencies from your system's package manager:
> - `xdotool`
> - `wmctrl`

Did you install those packages?

For example on Fedora you could do:

```
sudo dnf install xdotool wmctrl
```

or via GUI with `dnfdragora`.

On Ubuntu you could do:

```
sudo apt install xdotool wmctrl
```

or via GUI with Synaptic Package Manager.

**Comment by Merrit** [comment]
Closing for lack of further information.
