### ISSUE TITLE
Question about games with anti-cheat

### ISSUE THREAD

**Issue by BigBoyBarney** [Merrit/nyrna#159]
Hey! 
I've been playing around with Nyrna for the past few days and it works like a charm. Thank you so much!!

This might be a very dumb question, but I've been wondering how this interacts with anti-cheats. I've read that you're using the NtSuspendProcess system call. Is that something that's possibly cheat flaggable?

Thanks in advance!

**Comment by Merrit** [comment]
Hey there! Glad to hear it has been useful to you. :grinning: 

Anti-cheat algorithms are usually fairly strict; I know that they often prevent Nyrna from working at all, but if the game was suspended I expect that it probably would trigger something. I haven't heard of it happening though, so I can't say for sure! :blue_heart:

**Comment by BigBoyBarney** [comment]
Thank you! I won't mess with it too much then 😂
