### ISSUE TITLE
[Feature Request] Auto-suspend on minimize

### ISSUE THREAD

**Issue by bubufofo** [Merrit/nyrna#16]
auto suspend whitelisted exe files on minimizing them in w10

**Comment by Merrit** [comment]
Interesting idea. Will add that to the features wishlist!

**Comment by jjw410** [comment]
I was about to suggest a similar improvement, was wondering if it would be possible to have Nyrna minimise the application before suspending it, something to give it a more professional look. So it doesn't just look like the computer's locking up. Thanks so much for making this btw, I'm not a programmer but love that people can make awesome stuff like this :)

**Comment by Merrit** [comment]
So glad it has been useful to you!

Even if you aren't a programmer, excellent suggestions like this *are* quite helpful! I had never thought of having it minimize first, that really does sound like a nice option! Thank you :heart: 

btw, this is my first project; I just picked up programming on my own. So never say never :wink:

**Comment by jjw410** [comment]
> btw, this is my first project; I just picked up programming on my own. So never say never 😉

I have been finding a lot of these projects and have been getting into contributing to RPCS3 community! So maybe a little programming know-how wouldn't go a-miss now that the world is ending.

**Comment by Merrit** [comment]
There are many requirements in the open source community for success, including bug reports, feature suggestions, documentation, translations.. all things that help everything come together, and quite important in their own right.

For example I can say I have used some large open source projects that had terrible / no documentation, and it was a nightmare even if the software itself was good. So contributions of all kinds are very much appreciated :heart:

**Comment by jjw410** [comment]
I have been currently very disappointed with the lack of documentation on the RPCS3 wiki, lots of stuff that mods will tell you but nobody's written down. I totally know what you mean. I've starred this repository and if I can contribute anything more I'll pop back up! 😄

**Comment by Merrit** [comment]
Alpha preview of minimize on suspend build is available (Linux only): https://github.com/Merrit/nyrna/releases/tag/v1.4-alpha

@jjw410 I don't know if you use Linux, but since you suggested this feature I thought I'd offer you the chance to test it. :+1:

**Comment by Merrit** [comment]
Windows being minimized on suspend is now implemented (for Linux) as of v2.0-alpha.1

Same will be available for Windows targeting upcoming v2.0-beta.1

Automatically suspending whitelisted minimized windows will be considered for v2.1 or 2.2

**Comment by Merrit** [comment]
Automatically minimizing windows is available as of v2.0.

Automatically suspending certain windows when minimized is I believe out of the scope of this project however.
