### ISSUE TITLE
Consistent Crashing

### ISSUE THREAD

**Issue by DKGK1** [Merrit/nyrna#176]
Using this feature to pause Remnant from the Ashes. It works well for short periods, but always leads to a crash if left suspended for longer than an hour or two. Not sure if it's just this game, I haven't tried it on others yet.

**Comment by Merrit** [comment]
Some apps / games will not respond well to being suspended, just they way they are made. Please try with a couple other things to check if it is just this game. (You can also suspend things like a simple text editor or calculator to test :))
