### ISSUE TITLE
Feature Request - Specify a window/app to pause/unpause instead of active window

### ISSUE THREAD

**Issue by JReming85** [Merrit/nyrna#177]
Hi there,

Loving the program so far and seems to be better then my previous setup of using Cheat Engine to pause the process or set the speed to 0.01

However could you possible add a new feature to add a hotkey to suspend a predefined window/application?

I mainly use this for gaming, and I generally use a controller while also not having the game window as active.. (browsing web, watching videos or anime, etc) and would like to just pause without needing to click back into the game.

Think this is a feature you would be interested in implementing?

**Comment by Merrit** [comment]
I will give it some thought :)

**Comment by Merrit** [comment]
I added the ability to assign a hotkey to specific apps.

Please give this a try and let me know if that works for you. :)

[Nyrna-Windows-Portable.zip](https://github.com/Merrit/nyrna/files/12232877/Nyrna-Windows-Portable.zip)
[Nyrna-Linux-Portable.tar.gz](https://github.com/Merrit/nyrna/files/12232883/Nyrna-Linux-Portable.tar.gz)

**Comment by JReming85** [comment]
You are a rockstar!!!
Testing it now

**Comment by JReming85** [comment]
Not sure whats goings on but it keeps crashing on Win 11 for me



Faulting application name: nyrna.exe, version: 2.16.0.0, time stamp: 
0x64c94c5b

Faulting module name: ucrtbase.dll, version: 10.0.22621.436, time stamp: 
0xf5fc15a3

Exception code: 0xc0000409

Fault offset: 0x000000000007f61e

Faulting process id: 0x0x79B4

Faulting application start time: 0x0x1D9C4C0572AEEFC

Faulting application path: C:\Users\Jeremyr\AppData\Roaming\Nyrna\nyrna.exe

Faulting module path: C:\WINDOWS\System32\ucrtbase.dll

Report Id: e687ee2d-9680-427b-abea-3ea184d5ba0c

Faulting package full name:

Faulting package-relative application ID:

**Comment by Merrit** [comment]
That is weird. I'll spin up a Windows 11 machine so I can test it.

**Comment by JReming85** [comment]
Appreciate it, might be time to reinstall windows on my main pc… or switch to linux full time

**Comment by Merrit** [comment]
Alright, think I have fixed that now. Please give this one a try. :crossed_fingers: 

[Nyrna-Windows-Portable.zip](https://github.com/Merrit/nyrna/files/12242265/Nyrna-Windows-Portable.zip)
[Nyrna-Linux-Portable.tar.gz](https://github.com/Merrit/nyrna/files/12242268/Nyrna-Linux-Portable.tar.gz)

**Comment by JReming85** [comment]
This is awesome, thank you again for working on this!

**Comment by Merrit** [comment]
I'll take it that means it works for you :grin:

**Comment by JReming85** [comment]
>
> Sorry for the late update.  Yes it was working great.
>

Seemed to have a bit of delay in the game I was playing but will test it
with others tonight

**Comment by JReming85** [comment]
My keyboard has F1-F22 and I generally use F23-F24 for my controller.

It was originally set to F24 and I tried setting
F15, F19, F20, Insert, Delete

No combos but can give it a shot later today.

Also it looks like it's having trouble accessing the logging file and I
have seen that same error attached up to 3 times when toggling verbose
logging on/off

Hope this helps, lmk if you need me to try anything else

**Comment by JReming85** [comment]
Looking good,

Logging just shows `There was an issue creating the log file.` but I feel you already know that.

Can set/change both global + specific hotkeys just time.

1 thing I noticed, which you might not have implemented yet is the **Verbose Logging** is not persistant across restarts and the still 3-5 sec actual pause delay.

But great job!

**Comment by Merrit** [comment]
> Logging just shows `There was an issue creating the log file.` but I feel you already know that.

Yeah, Windows being Windows. I will continue looking into it, thanks for bringing it to my attention! :)

> Verbose Logging is not persistent across restarts

That will be in the next build.

> pause delay

Might not be a whole lot to do about this, Windows makes this sort of thing nearly impossible. I'll add it to the todo list to see if it can be improved. 

> Can set/change both global + specific hotkeys just time.

:tada: Glad to hear it is working now! Thanks again for the troubleshooting, you gave great info and it was a big help. 💙

**Comment by JReming85** [comment]
Looking forward to the next build.



Just want to say the previous official release does an instant pause for me, 
just the specific app build delays the pause.

**Comment by Merrit** [comment]
Hmm, after testing it some more I can only reproduce the issue on Windows 11; both Windows 10 and Linux suspend instantly, though for me it also happens with the most recent stable build.

**Comment by Merrit** [comment]
@JReming85 

Windows performance should see a marked improvement with [v2.17.0](https://github.com/Merrit/nyrna/releases/tag/v2.17.0). :tada:

**Comment by JReming85** [comment]
Awesome, thank you!
