### ISSUE TITLE
Windows Setup uses fixed version

### ISSUE THREAD

**Issue by Trenly** [Merrit/nyrna#179]
The inno setup script uses a fixed version `2.9.0` as the app version. This writes an incorrect value to the registry when the program is installed and makes it impossible for package managers like [winget](https://github.com/microsoft/winget-pkgs) to detect an upgrade is available. The script should use whatever version is being used for the GitHub release tag

https://github.com/Merrit/nyrna/blob/main/packaging/windows/inno_setup.iss#L3

**Comment by Merrit** [comment]
Excellent point, thanks for pointing that out!

I will look at automating the version for the next release :)
