### ISSUE TITLE
Nyrna starts but never loads

### ISSUE THREAD

**Issue by TearOfTheStar** [Merrit/nyrna#180]
Hello! 

Nyrna stopped running properly, it starts, i can enter settings and change things there, but main functionality doesn't work. It seems like something is missing in my system, but log isn't clear.
 
Last version that runs is 2.0 stable. After that this issue persists.

Win 10 x64 22h2 (19045.2846)

Installed on non system drive.

Log from 2.16.0 is attached.

[nyrna_v2.16.0_log.txt](https://github.com/Merrit/nyrna/files/12320142/nyrna_v2.16.0_log.txt)

**Comment by Merrit** [comment]
Please try installing the latest version of [PowerShell](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.3) and see if that makes any difference.

**Comment by Merrit** [comment]
That sounds very odd..

Please try running this in a terminal: `where.exe powershell`

Paste the output here.. from the logs it sounds like it can't find PowerShell.

**Comment by Merrit** [comment]
Interesting, never seen that not be on path before! Strange that they changed the executable name, but hey - glad you got it sorted! :tada: 

Thanks for providing clear troubleshooting info :)
