### ISSUE TITLE
v2.16.0 and v2.16.1 slow while suspending tasks and startup problem

### ISSUE THREAD

**Issue by iniv189** [Merrit/nyrna#183]
In the v2.15.0 is nothing happening the same thing, for some reason when i press the Pause hotkey it takes few seconds to suspend the task in those versions. also realize that the startup with windows is not working well, to nyrna proprely seems like it needs adm persmission but if admin is enabled the app does not open. i even tried with task schedule and the same issue keeps happening.

**Comment by Merrit** [comment]
Hi, thanks for the report!

I am looking into why it is suspending / resuming more slowly. What version of Windows are you using?

> startup with windows is not working well

In what way is it not working well? Does it not start when you sign into your computer? Please go into the settings for Nyrna and turn the "Start automatically at system boot" off, then back on, and try restarting your computer again to see if it works.

**Comment by iniv189** [comment]
I tried the "Start automatically at system boot" but did not work, i also tried to put inside the shell:startup folder but did not work. 
but if i disable the run as admin the app start normally but does not suspend somethings. (i will look more carefully the phenomenom and then i write here)

and i'm using https://i.imgur.com/k9gsAJa.png Version 22H2 (OS Build 19045.2965) windows 10

**Comment by Merrit** [comment]
Windows has issues running programs as admin on startup: https://superuser.com/questions/929225/how-to-run-a-program-as-an-administrator-at-startup-on-windows-10

I'm afraid this is a quirk of their operating system, and not to do with Nyrna.

I will release a new version soon that should greatly improve the speed and performance on Windows. :)

**Comment by Merrit** [comment]
Performance issue should hopefully be resolved (and then some!) with [v2.17.0](https://github.com/Merrit/nyrna/releases/tag/v2.17.0). :tada:
