### ISSUE TITLE
Controller support

### ISSUE THREAD

**Issue by super-lurker** [Merrit/nyrna#188]
Xinput/SDL support would be a amazing feature to see, considering this software is aimed at video games

**Comment by super-lurker** [comment]
So I can use nyrna and [playnite](https://github.com/JosefNemec/Playnite) at fullscreen mode on my couch with nothing but a controller for a console like experience.

I could use AutoHotkey to call nyrna but having a native function would even be better.

**Comment by Merrit** [comment]
I may consider this in the future.

For now, a gamepad chord can be remapped as you said..

Linux: I use [input-remapper](https://github.com/sezanzeb/input-remapper) for this all the time, Steam gamepad config works too from experience
Windows: Should be able to use [PowerToys](https://learn.microsoft.com/en-us/windows/powertoys/keyboard-manager) / Steam / AutoHotKey / etc

*****

For reference for anyone else who comes across this:

In `input-remapper` I tell it that...

- when I press `Guide` + `Select` on my controller, it should remap that to simulate pressing `R_Shift` + `F12` - which toggles MangoHud
- when I press `Guide` + `Dpad up` it should remap to `VOLUME_UP`
- when I press `Guide` + `Start` it should remap to `Pause` to trigger Nyrna. Etc.

**Comment by Merrit** [comment]
This would add a fair amount of complexity to the app, and is easily handled with 3rd party tools (as mentioned above).

For now I am going to say this is not planned.
