### ISSUE TITLE
Silent startup

### ISSUE THREAD

**Issue by super-lurker** [Merrit/nyrna#189]
silent startup/minimized to tray, would be a welcomed feature.

**Comment by Merrit** [comment]
Thanks for the idea, will look into adding this! 💙

**Comment by Redemp** [comment]
> Thanks for the idea, will look into adding this! 💙

:pray:

**Comment by Merrit** [comment]
This is actually already a thing, but it requires `Close to tray` to be enabled so the user doesn't end up with Nyrna running in the background and no way to know or interact with it.

I am patching that to make it more obvious and automatic! :+1:

**Comment by Merrit** [comment]
Should be resolved with [v2.17.1](https://github.com/Merrit/nyrna/releases/tag/v2.17.1). Thanks for the issue! :grinning: :tada:
