### ISSUE TITLE
Exclude Nyrna from suspension

### ISSUE THREAD

**Issue by user18081972** [Merrit/nyrna#190]
If i press the suspend hotkey while in the Nyrna window, it suspens Nyrna, with no easy way to unsuspend it.
Why not exclude Nyrna from suspending itself?

**Comment by Merrit** [comment]
Yep, that was in place for the GUI but it was missed for the hotkey. Thanks for pointing that out! :tada:

**Comment by Merrit** [comment]
Should be resolved with [v2.17.1](https://github.com/Merrit/nyrna/releases/tag/v2.17.1). Thanks for the issue! :grinning: :tada:
