### ISSUE TITLE
Doesn't really work

### ISSUE THREAD

**Issue by apoklyps3** [Merrit/nyrna#194]
I tried to suspend eftooball 2024, my computer almost died.
Mouse was lagging like 10 seconds back, everything unresponssive, and CPU usage + Memory usage wasn't even 50%

**Comment by Merrit** [comment]
It looks like they've [added an anti-cheat to the game](https://steamcommunity.com/app/1665460/discussions/0/3807283698653633699/?ctp=3).

Anti-cheat breaks a lot of tools, Nyrna included. Let them know their new anti-cheat is something you don't like. 💙
