### ISSUE TITLE
Tray icon buttons not working (win11)

### ISSUE THREAD

**Issue by user18081972** [Merrit/nyrna#195]
![image](https://github.com/Merrit/nyrna/assets/124319511/8524ac1e-11af-4eb9-be5b-a523fca7a3e9)

Neither Hide, Show or Exit work on my 2 Windows 11 PCs.
Hide doesnt minimize or hide the window
Show doesnt raise the window, exit does nothing atall
v2.17.1

**Comment by Merrit** [comment]
Seems to be working in my tests.. 

Please go in to Nyrna's settings:

![image](https://github.com/Merrit/nyrna/assets/9575627/5f9a0371-78ad-422d-9187-ccf92b66e0e5)

- Enable verbose logging
- Exit/reopen Nyrna
- Reproduce the issue (try to use the tray buttons)
- In settings, view the logs
- Click "Copy logs"
- Paste the logs here

**Comment by Merrit** [comment]
Thanks, that was very helpful!

I made a change, please try it and see if it works as expected now:

[Nyrna-Windows-Portable.zip](https://github.com/Merrit/nyrna/files/13190733/Nyrna-Windows-Portable.zip)

**Comment by Merrit** [comment]
Excellent! Thank you again for helping debug that :grin:  💙
