### ISSUE TITLE
Red dead redemption 2 error to suspend

### ISSUE THREAD

**Issue by ErayOzcanUCLL** [Merrit/nyrna#197]
Greetings
I wanted to test this application out on a game RDR2. I got an error and the possible reason in the error was that it could be because of anti cheat. I have searched it up but this game does not have any anti-cheat. Is there something i am doing wrong or is it a limitation of   Nyrna?
logs:

`
--------------------------------------------------------------------------------

2023-10-31 21:01:38

--------------------------------------------------------------------------------

2023-10-31 21:03:45

   INFO ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO │ #0   LoggingManager.initialize (package:nyrna/logs/logging_manager.dart:58)
   INFO │ #1   <asynchronous suspension>
   INFO ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
   INFO │ 💡 Logger initialized.
   INFO └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO │ #0   _WindowTileState.build.<anonymous closure>.<anonymous closure> (package:nyrna/apps_list/widgets/window_tile.dart:94)
   INFO │ #1   _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1154)
   INFO ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
   INFO │ 💡 WindowTile clicked: Window(id: 12781702, process: Process(executable: RDR2.exe, pid: 12888, status: ProcessStatus.normal), title: Red Dead Redemption 2)
   INFO └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO │ #0   AppsListCubit.toggle (package:nyrna/apps_list/cubit/apps_list_cubit.dart:130)
   INFO │ #1   <asynchronous suspension>
   INFO ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
   INFO │ 💡 Beginning suspend for window: Window(id: 12781702, process: Process(executable: RDR2.exe, pid: 12888, status: ProcessStatus.normal), title: Red Dead Redemption 2)
   INFO └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO │ #0   Win32.minimizeWindow (package:nyrna/native_platform/src/win32/win32.dart:104)
   INFO │ #1   AppsListCubit._minimize (package:nyrna/apps_list/cubit/apps_list_cubit.dart:256)
   INFO ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
   INFO │ 💡 Minimizing window with id 12781702
   INFO └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO │ #0   Win32ProcessRepository.suspend (package:nyrna/native_platform/src/process/repository/src/win32_process_repository.dart:108)
   INFO │ #1   AppsListCubit._suspend (package:nyrna/apps_list/cubit/apps_list_cubit.dart:244)
   INFO ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
   INFO │ 💡 Suspending 12888 was successful: false
   INFO └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO │ #0   Win32.restoreWindow (package:nyrna/native_platform/src/win32/win32.dart:111)
   INFO │ #1   AppsListCubit._restore (package:nyrna/apps_list/cubit/apps_list_cubit.dart:268)
   INFO ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
   INFO │ 💡 Restoring window with id 12781702
   INFO └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO │ #0   AppsListCubit.toggle (package:nyrna/apps_list/cubit/apps_list_cubit.dart:138)
   INFO │ #1   <asynchronous suspension>
   INFO ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
   INFO │ 💡 suspend was successful: false
   INFO └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO │ #0   AppsListCubit.toggle (package:nyrna/apps_list/cubit/apps_list_cubit.dart:140)
   INFO │ #1   <asynchronous suspension>
   INFO ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
   INFO │ 💡 Window after interaction: Window(id: 12781702, process: Process(executable: RDR2.exe, pid: 12888, status: ProcessStatus.normal), title: Red Dead Redemption 2)
   INFO └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

--------------------------------------------------------------------------------

2023-10-31 21:04:16

   INFO ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO │ #0   LoggingManager.initialize (package:nyrna/logs/logging_manager.dart:58)
   INFO │ #1   <asynchronous suspension>
   INFO ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
   INFO │ 💡 Logger initialized.
   INFO └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO │ #0   main (package:nyrna/main.dart:53)
   INFO │ #1   <asynchronous suspension>
   INFO ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
   INFO │ 💡 Starting Nyrna v2.17.2
   INFO └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO │ #0   HotkeyService.addHotkey (package:nyrna/hotkey/hotkey_service.dart:34)
   INFO │ #1   <asynchronous suspension>
   INFO ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
   INFO │ 💡 Registered hotkey: Pause
   INFO └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO │ #0   LoadingCubit.checkDependencies (package:nyrna/loading/cubit/loading_cubit.dart:23)
   INFO │ #1   new LoadingCubit (package:nyrna/loading/cubit/loading_cubit.dart:19)
   INFO ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
   INFO │ 💡 Checking dependencies..
   INFO └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO │ #0   _WindowTileState.build.<anonymous closure>.<anonymous closure> (package:nyrna/apps_list/widgets/window_tile.dart:94)
   INFO │ #1   _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1154)
   INFO ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
   INFO │ 💡 WindowTile clicked: Window(id: 12781702, process: Process(executable: RDR2.exe, pid: 12888, status: ProcessStatus.normal), title: Red Dead Redemption 2)
   INFO └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO │ #0   AppsListCubit.toggle (package:nyrna/apps_list/cubit/apps_list_cubit.dart:130)
   INFO │ #1   <asynchronous suspension>
   INFO ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
   INFO │ 💡 Beginning suspend for window: Window(id: 12781702, process: Process(executable: RDR2.exe, pid: 12888, status: ProcessStatus.normal), title: Red Dead Redemption 2)
   INFO └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO │ #0   Win32.minimizeWindow (package:nyrna/native_platform/src/win32/win32.dart:104)
   INFO │ #1   AppsListCubit._minimize (package:nyrna/apps_list/cubit/apps_list_cubit.dart:256)
   INFO ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
   INFO │ 💡 Minimizing window with id 12781702
   INFO └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO │ #0   Win32ProcessRepository.suspend (package:nyrna/native_platform/src/process/repository/src/win32_process_repository.dart:108)
   INFO │ #1   AppsListCubit._suspend (package:nyrna/apps_list/cubit/apps_list_cubit.dart:244)
   INFO ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
   INFO │ 💡 Suspending 12888 was successful: false
   INFO └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO │ #0   Win32.restoreWindow (package:nyrna/native_platform/src/win32/win32.dart:111)
   INFO │ #1   AppsListCubit._restore (package:nyrna/apps_list/cubit/apps_list_cubit.dart:268)
   INFO ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
   INFO │ 💡 Restoring window with id 12781702
   INFO └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO │ #0   AppsListCubit.toggle (package:nyrna/apps_list/cubit/apps_list_cubit.dart:138)
   INFO │ #1   <asynchronous suspension>
   INFO ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
   INFO │ 💡 suspend was successful: false
   INFO └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   INFO │ #0   AppsListCubit.toggle (package:nyrna/apps_list/cubit/apps_list_cubit.dart:140)
   INFO │ #1   <asynchronous suspension>
   INFO ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
   INFO │ 💡 Window after interaction: Window(id: 12781702, process: Process(executable: RDR2.exe, pid: 12888, status: ProcessStatus.normal), title: Red Dead Redemption 2)
   INFO └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
`

**Comment by Merrit** [comment]
Thanks for opening the issue! I will take a look at it when I get a chance and see if there is something special about this case.

**Comment by Merrit** [comment]
Seems to work over here, at least on a cracked copy. Leads me to believe there is something about their DRM causing the issue, or something about your computer specifically.

What version of Windows are you using?

Try suspending it from the Resource Monitor manually:

- In Start menu search for `Resource Monitor`
- Find the program in the list, probably `RDR2.exe`
- Right click it and select `Suspend`
- Check if the column for `Status` has changed to `Suspended` or not

**Comment by ErayOzcanUCLL** [comment]
I have a cracked copy as well. I have a Windows 11 home version 10.0.22631 Build 22631. 
I have followed your steps and rdr2 does suspend and i can resume the process and all works well. When i try to do it with Nyrna, i still get the this window: 
![image](https://github.com/Merrit/nyrna/assets/113980911/64bd8dc9-1ed9-4068-87b8-32042ba38529)

**Comment by ErayOzcanUCLL** [comment]
I have the 1311.23 build by EMPRESS + Mr_Goldberg a FitgirlRepack. its weird that the suspending of the game through windows itself works but not with Nyrna.. doesnt nyrna normally do the same thing in the windows resource monitor?

**Comment by Merrit** [comment]
Possibly, but there isn't really any way to know. Everything Windows is closed-source, so we can't see how the Resource Monitor does it, and the API that Nyrna uses to suspend and resume are undocumented, unofficial, and not supported.

On Linux I could easily compare implementations, but on Windows...

¯\\\_(ツ)_/¯

**Comment by ErayOzcanUCLL** [comment]
I really thought I had tried this but seems like that's not true. When Nyrna is run with administrator rights, then it does work.
