### ISSUE TITLE
gendesk: command not found

### ISSUE THREAD

**Issue by Casul51** [Merrit/nyrna#2]
System - Manjaro

Pamac error:
/var/tmp/pamac-build-casual/nyrna/PKGBUILD: line 15: gendesk: command not found

**Comment by Casul51** [comment]
Fixes after installing gendesk
So, add to dependencies

**Comment by Merrit** [comment]
Yep, I missed that.

I just pushed aeb5f80b13ade4c094cc87703acd68216cc28088 which should fix this.

Thank you for the report! :)
