### ISSUE TITLE
Nyrna binary compiled with glibc-2.32

### ISSUE THREAD

**Issue by BlueManCZ** [Merrit/nyrna#20]
I noticed that Nyrna binary is compiled with glibc version 2.32. When I try to run it I get error:
> ./nyrna: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./nyrna)

because I use glibc-2.31 which is stable in my system. It is not big deal for me, because I compile Nyrna myself from source. I just wanted to let you know that glibc-2.32 is not stable in all distributions yet.

https://packages.gentoo.org/packages/sys-libs/glibc

**Comment by Merrit** [comment]
Thanks for the report!

I will look into setting up builds inside a Docker container that uses only stable packages to build with. :+1:

**Comment by Merrit** [comment]
Hey there, sorry for the delay!

Nyrna is now compiled on Ubuntu LTS, so this sort of thing should hopefully not be an issue going forward.

Thanks for the great bug report! :heart:
