### ISSUE TITLE
Can't launch Nyrna with latest Nobara update

### ISSUE THREAD

**Issue by TheISOmorph** [Merrit/nyrna#200]
As per the title, Nyrna can't be launched anymore since I updated my system a couple of hours ago.

**Launching in console produces following messages:**

> $ flatpak run codes.merritt.Nyrna
> 
> (nyrna:2): Gtk-WARNING **: 06:55:12.436: Locale not supported by C library.
>         Using the fallback 'C' locale.
> Gtk-Message: 06:55:12.436: Failed to load module "xapp-gtk3-module"
> 
> (nyrna:2): Gdk-CRITICAL **: 06:55:12.454: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
> libGL error: No matching fbConfigs or visuals found
> libGL error: failed to load driver: radeonsi
> libGL error: No matching fbConfigs or visuals found
> libGL error: failed to load driver: radeonsi
> libGL error: No matching fbConfigs or visuals found
> libGL error: failed to load driver: swrast
> 
> ** (nyrna:2): WARNING **: 06:55:12.524: Failed to start Flutter renderer: Unable to create a GL context
> 
> ** (nyrna:2): WARNING **: 06:55:37.526: atk-bridge: get_device_events_reply: unknown signature

**System specs:**

> OS: Nobara release 38 (Thirty Eight) x86_64 
> Host: B550 AORUS ELITE AX V2 
> Kernel: 6.6.3-201.fsync.fc38.x86_64 
> Uptime: 1 hour, 19 mins 
> Packages: 3382 (rpm), 18 (flatpak) 
> Shell: bash 5.2.15 
> Resolution: 2560x1440, 2560x1440 
> DE: Plasma 5.27.9 
> WM: KWin 
> Theme: [Plasma], Breeze [GTK2/3] 
> Icons: Papirus [Plasma], Papirus [GTK2/3] 
> Terminal: konsole 
> CPU: AMD Ryzen 7 5800X (16) @ 3.800GHz 
> GPU: AMD ATI Radeon RX 6800/6800 XT / 6900 XT 
> Memory: 7538MiB / 31991MiB 

**Installed Packages:**

> Name         : mesa-libGL
> Version      : 23.3.0
> Release      : 1.fc38
> Architecture : i686
> Size         : 535 k
> Source       : mesa-23.3.0-1.fc38.src.rpm
> Repository   : @System
> From repo    : nobara-baseos-multilib
> Summary      : Mesa libGL runtime libraries
> URL          : http://www.mesa3d.org
> License      : MIT AND BSD-3-Clause AND SGI-B-2.0
> Description  : Mesa libGL runtime libraries.

I already tried completely uninstalling the flatpak with all settings and reinstalling. No change in behaviour.

**Comment by TheISOmorph** [comment]
Thank you for looking into this.

The portable version does start! 
However, as soon as I try to suspend an app, it just minimizes and Nyrna becomes unresponsive and I have to kill the process.

**Comment by TheISOmorph** [comment]
I did a downgrade to mesa 23.2.1 and got it working again for the time being.
For Fedora / Nobara users:

> sudo dnf downgrade mesa-libGL

**Comment by Merrit** [comment]
Glad to hear it is working for you. Sounds like a bug with mesa, hopefully they will push a fix for it soon.

**Comment by Merrit** [comment]
I just tested [Nyrna v2.18.0](https://github.com/Merrit/nyrna/releases/tag/v2.18.0) in Nobara, and it seems to be working.

**Comment by TheISOmorph** [comment]
I just updated to Nobara 39 and can confirm everything is working fine with Nyrna 2.18
Thank you and happy new year!

**Comment by Merrit** [comment]
Great to hear! Happy new year :tada:
