### ISSUE TITLE
Font is weirdly wide

### ISSUE THREAD

**Issue by K0-RR** [Merrit/nyrna#203]
It looks like there are two or three spaces between every word

![image](https://github.com/Merrit/nyrna/assets/43277609/a1cfedf7-c4cf-4865-90d4-f19037ea0192)
![image](https://github.com/Merrit/nyrna/assets/43277609/860da6d2-d01c-49b2-91e0-e643a5a8006f)

**Comment by Merrit** [comment]
This is happening because your distro (Rhino Linux) doesn't have the Roboto fonts installed.

You can resolve it by installing the fonts:

```
sudo apt install fonts-roboto
```

Most distros have these fonts installed by default.
