### ISSUE TITLE
[Feature Request] [Windows] Suspend child processes

### ISSUE THREAD

**Issue by unphased** [Merrit/nyrna#206]
i tried it last year in windows but it sadly did not work in many games. for example RDR2.

i hope to have better luck with it in Linux, but it would help me to reason about how it may interact with a given application if I had a working understanding of what tools and interfaces with the operating are being used to suspend processes.

**Comment by Merrit** [comment]
Games with onerous DRM and/or anti-cheat software will often not work, specifically because those things work to block outside software from affecting them. To my knowledge RDR2 is one of those; the solution in these cases is to complain to the company about their use of draconian and anti-consumer software like that. It _may_ work better on Linux since it will be suspending the Linux emulation process rather than the native Windows process.

As to how it works, essentially it boils down to:

- Linux: uses [kill](https://man7.org/linux/man-pages/man1/kill.1.html) to suspend and resume the processes
- Windows: uses the undocumented `NtSuspendProcess` and `NtResumeProcess` win32 api calls

**Comment by unphased** [comment]
Thank you.

You bring up a good point that DRM middlewares routinely do unsavory things that can interfere with normal operation of the computer and this is an example. A developer may easily implement an architecture that foils this scheme, for example a simple watchdog process could shut things down if the main process is found to be unresponsive. 

I may suggest a feature, if we could (and it usually is easy to) identify a number of processes associated with some app, being able to suspend them all and then resume them all simultaneously might provide more compatibility. 

My hunch from playing around with this and other tools on windows (where we have access to the likes of process monitor/process lasso) is that this might do the trick. On Linux I'd also be able to do quick hacks with shell scripts, but hadn't explored it.

**Comment by Merrit** [comment]
The Linux implementation already suspends and resumes all associated processes: https://github.com/Merrit/nyrna/blob/53381a6cdb69aee52ae22a07b0418ff477701977/lib/native_platform/src/process/repository/src/linux_process_repository.dart#L138-L155

The Windows implementation does not as yet do so. It may indeed help with such situations, though I could also see it causing instability given how flaky Windows reacts to such things already.

**Comment by Merrit** [comment]
With the games that have given you problems, and specifically Red Dead 2; have you tried running Nyrna as administrator?

**Comment by unphased** [comment]
that is something i did not think to try, i am very excited to try that next time! 

i dont game very much these days outside of low spec games on my steam deck and valve has completely solved the pausing issue there by making suspend really awesome. although, if you forget the device for two weeks it will certainly die by then, and you still lose progress.

i'll be sure to report back and work with you on issues. my RDR2 install and savegames died with my inland 4TB NVMe drive however. it's not certain i will play that game again. it's spectacular but the pace is slow. my plan is to find a savegame online for near where i was and continue.

**Comment by Merrit** [comment]
Sorry to hear about your save being lost! Hardware failures are the worst!

Since this sounds a lot like https://github.com/Merrit/nyrna/issues/197, I will close this for now. If you encounter the issue again while running Nyrna as admin, feel free to reopen or start a new issue. :)

**Comment by unphased** [comment]
Tell ya what, i have no issues so far running Nyrna as admin. I think you may want to give this at least as a suggestion in the readme. I will test more and try to compare with and without running as admin, but so far the experience is really great. I have 64GB in this machine and it is a game changer because it seems like the OS can swap idle processes out, so it sure looks like I can run 2, 4, probably even more games at the same time. Maybe it's going to fuel my ADD further, but this completely changes the experience and allows gaming sessions to naturally have a lot more variety when you can pause and resume a number of (presumably non-multiplayer) games at will. 

Thank you so much for making this tool, I really like how it will auto focus the game you unpause to bring you right back into the action.

**Comment by Merrit** [comment]
I am glad to hear it is useful to you! :blue_heart: 

A suggestion to run as admin was added with v2.18.0 if suspend/resume fails.

I also added a mention to the README just now with 03f584fd2689171af153b9a299c0384d4da66ea1.
