### ISSUE TITLE
[Feature Request] Different Hotkeys for Suspend and Resume

### ISSUE THREAD

**Issue by Petkov0721** [Merrit/nyrna#208]
Is it possible to have different hotkeys for suspend and for resume?
Right now the hotkey for resume and suspend is always the same, it would be really useful to be able to set different hotkeys for resume and for suspend independantly.

Thank you!

**Comment by Merrit** [comment]
Could you give me an idea of your use case? I am not sure how this would be helpful.

**Comment by Petkov0721** [comment]
Thank you for your response.

I have a script that suspends and resumes a game when streaming via Sunshine (https://github.com/LizardByte/Sunshine). 
However, it's inconsistent. When connecting, it attempts to find the game (via it's .exe) and resume it if suspended, but sometimes it suspends the active window instead.

Having separate keys would be helpful. I could pass the resume keys from the script, and if a game is suspended, it would resume it without affecting the active window. If nothing is suspended, it would do nothing.

It's an edge case, but it provides users with more options I guess.

**Comment by Merrit** [comment]
I am still not quite sure what you are trying to achieve. Do the app-specific hotkeys not work for this use case?

![image](https://github.com/Merrit/nyrna/assets/9575627/f1aa0f98-029c-4a3c-9e14-4dd7b0fcb3fb)

Then you don't have to worry about the hotkey accidentally targeting the incorrect window.
