### ISSUE TITLE
[Feature Request] Notifications

### ISSUE THREAD

**Issue by MR-Diamond** [Merrit/nyrna#21]
I am on Linux, Xfce.
In the Xfce's preferences I set the notifications timeout duration to six second, and in facts, the notifications of Nyrna respects this settings. However would be useful to have a way to increase the timeout/duration of Nyrna's notifications, to remember that an application has been paused; furthermore such notification could be also improved by display the time of when the application has been paused.

**Comment by Merrit** [comment]
So to confirm, your requests are:

- Override system's notification display length (not sure this is possible, will have to check.)
- Include in the notification the time application was suspended


Is that right?

**Comment by MR-Diamond** [comment]
Right. I also have opened a ticket on github, about.
I a Mr-Diamond  domenica, 01 novembre 2020, 04:07PM +01:00 da Merritt  notifications@github.com :

**Comment by Merrit** [comment]
The new version of Nyrna doesn't currently support notifications, and I think at this point such a feature is out of the scope of this project - at least given that I don't have the time to devote to it.
