### ISSUE TITLE
[Feature request] Button to add to favorites?

### ISSUE THREAD

**Issue by irwencena** [Merrit/nyrna#213]
I recently asked if it would be possible to recognize games and it is not possible, but it would not be bad to be able to choose a process and in the options mark it as a favorite, it is like I have many processes, when I suspend it goes to the top (pinned) but when I resume it it goes back to hide all the way down. with a section or way to add to favorites would be great and I guess something easy to implement? if you like the idea

![image](https://github.com/Merrit/nyrna/assets/75181921/be1781f1-ff1f-47f2-8462-c1558ae0fbba)

![image](https://github.com/Merrit/nyrna/assets/75181921/b3380b74-6ec0-4dc6-baa2-7788be57eba1)

**Comment by Merrit** [comment]
Interesting idea, thanks. I will give it some thought :)

**Comment by irwencena** [comment]
how its going????

**Comment by Merrit** [comment]
Been a bit backed up, so I haven't gotten to this as of yet. It is on my to-do list for when I get a little time for it though. :+1:
