### ISSUE TITLE
Elden Ring not suspending 

### ISSUE THREAD

**Issue by synacktic** [Merrit/nyrna#218]
Maybe something has changed, but since the readme.md mentions Elden Ring, I thought I would mention that it can't seem to suspend it. I'm running the latest Elden Ring on Windows 11.
OS: Windows 11
Game: Elden Ring
Nyrna: 2.20.0
User: As self and using "Run as administrator"

**Comment by Merrit** [comment]
Thanks for opening the issue!

I will try and find some time to boot into a Windows machine and try it out.

**Comment by synacktic** [comment]
Thank you! Little update... I had a hunch or two.

Not too interesting: I was able to suspend the whole system and the game worked upon resume.

Interesting: I launched it with the seamless coop mod, which disables Easy Anti-Cheat and Nyrna was able to suspend / resume it just fine. My  (rather obvious) guess is that this has something to do with Easy Anti-Cheat...

**Comment by Merrit** [comment]
Ah yeah, you've hit the nail on the head exactly.

Anti-cheat tools like that are designed specifically to prevent anything external from changing the application, so they definitely block Nyrna.

Not much that can be done on our end about that unfortunately, just one of the annoyances of anti-cheat software. At least the Elden Ring anti-cheat can be disabled relatively easily. :)

**Comment by Merrit** [comment]
Thanks for opening the issue!

I will try and find some time to boot into a Windows machine and try it out.
