### ISSUE TITLE
Suspend application to disk

### ISSUE THREAD

**Issue by NoUserNameForYou** [Merrit/nyrna#219]
Hello!

Brilliant app you created, thanks so much! I am mainly requesting this for Geforce Experience (works offline through LAN once you login while online) which will sunset Shield/Moonlight support when the Nvidia App goes out of Beta.

It'd be useful for people with unstable electricity as well. 

Thanks!

**Comment by Merrit** [comment]
Suspending to disk _may_ be possible on Linux, which is on my to-do for investigating when I have the time.

It is not possible on Windows.
