### ISSUE TITLE
Suspend all instances doesnt work.

### ISSUE THREAD

**Issue by elric274** [Merrit/nyrna#223]
![Screenshot (14238)_proc](https://github.com/user-attachments/assets/a0b4a41f-c926-4ca3-87d0-00cacc9a39eb)
hi I love your application and I will use it for the rest of my life.
I only have one little issue.
when I click on Suspend all instances only one process of chrome suspends and the rest stay active. and occasionally keep using cpu/disk. 
is it normal or a bug?

**Comment by Merrit** [comment]
Thanks for opening the issue!

Working as expected on here (Linux). I presume from your screenshot you are using Windows; 10 or 11?

When I have some time I will try it out on Windows and see what the difference might be.

**Comment by Merrit** [comment]
Should be fixed with cf171b8e98a73535d378c975063b610043b68009, which will be available in v2.23.0 shortly. :)

**Comment by elric274** [comment]
ty so much!
