### ISSUE TITLE
[BUG] High RAM comsuption while idle - Windows 10

### ISSUE THREAD

**Issue by 1024mb** [Merrit/nyrna#30]
**Describe the bug**
The app is using a lot of RAM (5GB as of writing this) doing nothing, since I started it I haven't suspended any application.

**To Reproduce**
1. Start the app.
2. Do nothing for several hours.

**Expected behavior**
Not to use so much RAM.

**Screenshots**
![ProcessHacker_2021-03-18_09-38-10](https://user-images.githubusercontent.com/9301204/111644305-9d42ba80-87f7-11eb-821f-5bf3b85dab8a.png)
![ProcessHacker_2021-03-18_09-37-55](https://user-images.githubusercontent.com/9301204/111644310-9e73e780-87f7-11eb-80ad-280456b6533d.png)

**Software (please complete the following information):**
 - OS: Windows 10

**Comment by Merrit** [comment]
Thanks for issue!

That is definitely odd, I haven't seen RAM use go beyond ~50MB, even after several hours.

Could you please try restarting your computer, and see if it happens again?

**Comment by Merrit** [comment]
Additionally, have you changed the frequency for Auto Refresh?

I was testing around and setting it to 1 second had me up to ~500mb RAM usage after a couple hours, setting it back to 5 seconds dropped it back down quite a lot.

**Comment by ceedveed** [comment]
I'm seeing the same thing. I suspended one game, then just monitored task manager to memory usage of Nyrna. It goes up every 5 seconds by 0.3-0.4 MB.

**Comment by Merrit** [comment]
I can confirm the RAM usage goes up over time, however at the default 5 seconds setting it was fairly stable, seems to go between 50mb - 300mb, up and down.

Obviously not great for something simple like Nyrna, however probably about the best we'll get given that the win32 API doesn't expose any reasonable method for handling processes the way we require - Linux was quite straightforward, but Windows required a lot of creative hacks to get working at all.

So far as I can see, the RAM usage seems to top out given a reasonable refresh rate or by using the manual refresh, it doesn't grow exponentially and infinitely. Has anyone else seen it climbing non-stop?

**Comment by 1024mb** [comment]
I haven't changed any setting either and mine reached to 5GB.
I have also noticed that in every refresh the RAM consumption increases as @ceedveed stated. Within 2 minutes it has reached 170MB and keeps increasing, disabling auto refresh stops that.

**Comment by Merrit** [comment]
I tried monitoring Nyrna for 24 hours, on my end it topped out at ~200mb of RAM.

I've yet to track down what might be causing it to go so high. Curious if you are both on Windows 10?

**Comment by ceedveed** [comment]
> I tried monitoring Nyrna for 24 hours, on my end it topped out at ~200mb of RAM.
> 
> 
> 
> I've yet to track down what might be causing it to go so high. Curious if you are both on Windows 10?

I'm on Windows 10 Pro 20H2

**Comment by 1024mb** [comment]
@Merrit I'm also on Windows 10.

**Comment by Merrit** [comment]
I'm afraid this may just be a limitation of Windows as their API currently stands. I am thinking to make auto-refresh disabled by default for Windows, along with a warning about the performance effects it has..

**Comment by Merrit** [comment]
A warning has been added and default set to off as of f7fae2a330cd8759eab619af12dd049220285b7a.

If I hopefully get the time I will try and take a look further at ways to work around this Windows limitation. 🌈

**Comment by Merrit** [comment]
Alright, I installed Windows on my computer and have been troubleshooting.

While the RAM consumption goes up a small amount over time without any interaction, the issue seems most prominent when a change is detected in the open windows, for example: when a window is opened or closed, or when the title of the window changes by doing something like changing tabs in a browser window -- each of these actions causes a definite jump in RAM consumption.

I will do some further troubleshooting and debugging..

**Comment by Merrit** [comment]
I believe this should be resolved as of 9dc2390cc3edcf079773f1224ce2a2771e1a6f4b

I've run Nyrna for about 24 hours, the computer seeing heavy use during the time and the highest I ever saw the RAM consumption go was ~75mb, often cleaning itself up to ~40mb.

Here is a dev build to test it out: [nyrna-windows-portable.zip](https://github.com/Merrit/nyrna/files/6941396/nyrna-windows-portable.zip)

**Comment by ceedveed** [comment]
Just wanted to also confirm that this issue is resolved based testing over a couple days using version 2.1.0. I've been suspending and resuming a game multiple times a day while also sleeping and waking the PC multiple times a day with Nyrna running the entire time.

My highest active memory usage is around 100 MB and commit size around 200 MB with auto-refresh set to 5 seconds.

**Comment by Merrit** [comment]
That's great to hear, thanks for confirming on your end! 😀 🌈

**Comment by 1024mb** [comment]
I have tested latest version too and so far it seems the bug has been fixed. Nyrna has been running for 8 hours now and is at 80.5 MB. Thank you!
