### ISSUE TITLE
[Feature Request] Suspend by pid

### ISSUE THREAD

**Issue by rejedai** [Merrit/nyrna#32]
Is it possible to suspend by process id? For example `nyrna -p $(pidof RDR2.exe)`.

**Comment by Merrit** [comment]
Nyrna doesn't have such a feature.. would something like PsSuspend be what you are wanting? https://docs.microsoft.com/en-us/sysinternals/downloads/pssuspend

**Comment by rejedai** [comment]
I am a Linux user. At the moment I use `kill -19` to stop the process, but I would to have **nyrna** functions like autominimize

**Comment by Merrit** [comment]
This is something you'd like to do from a command?

If so, it sounds ripe for a script. xdotool handles this stuff quite nicely, for example:

```
xdotool windowminimize `xdotool search --pid $pid`
```

I don't think Nyrna could make such a command easier than xdotool already does. What do you think?
