### ISSUE TITLE
Pitch Black Theme

### ISSUE THREAD

**Issue by BirtLaden** [Merrit/nyrna#44]
Hi Merrit

Fantastic app, put through donation.  Not a bug, but rather a feature request or directions on how I could make changes myself if possible?  Would like to create a pitch black Background with just the writing visible for the app, as I use it with an OLED TV on a pitch black background, and have the app permanently sitting open on my desktop.

Thanks 
Tony Birt

**Comment by Merrit** [comment]
Hi Tony

Many thanks for the donation, it is greatly appreciated! I am very gratified to hear you are finding Nyrna useful 😀 

I will look into creating a pitch black theme 👍

**Comment by Merrit** [comment]
I put together a theme switcher as of 8208972ce722836fe210222d7d9cbe78c5eb0f90

... this allows a choice of: dark, pitch black, or light.

![image](https://user-images.githubusercontent.com/9575627/126046331-32f21091-81b9-48ee-bce2-144bc2857af4.png)

If you'd be willing to test it out and report back that would be very helpful as I don't have an OLED screen to judge it on.

Downloads to try it are available here: https://github.com/Merrit/nyrna/releases/tag/v2.1.0-beta.1

**Comment by Merrit** [comment]
Updated packages that remember selected theme: https://github.com/Merrit/nyrna/releases/tag/v2.1.0-beta.2

**Comment by BirtLaden** [comment]
Works brilliant, thanks Kristen. Looks really good on Desktop beside
Launchbox, my main launcher.

**Comment by Merrit** [comment]
Glad to hear it! (Also, Launchbox looks cool 😀)
