### ISSUE TITLE
Windows Portable Detected as Trojan.

### ISSUE THREAD

**Issue by intelligentgaming** [Merrit/nyrna#52]
Downloading and running either of the Windows builds results in Windows 10 Defender flagging them as a trojan. 

Presumably a false positive.

**Comment by Merrit** [comment]
Thanks for the issue!

I will test this out & see about submitting a report to Microsoft about the false positives. :+1:

**Comment by Merrit** [comment]
I've submitted a review request to Microsoft for this, just waiting for them to process.

**Comment by Merrit** [comment]
Malware flag has been removed by Microsoft. I tested it in a VM, and I can now download without any issues.

If you'd like to force the update for your definitions rather than waiting you can:

```
1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"
```

Thanks again for the report! :grin: :+1:
