### ISSUE TITLE
[BUG] GetProperty: No such property

### ISSUE THREAD

**Issue by etam** [Merrit/nyrna#6]
**Describe the bug**
I tried running nyrna and it's not working. I get the following result:
```
2020/07/20 17:55:11 Hotkey was pressed:  Pause
2020/07/20 17:55:11 No saved process details found
2020/07/20 17:55:11 Window ID: 117440514
2020/07/20 17:55:11 GetProperty: No such property '_NET_WM_PID' on window 7000002.
2020/07/20 17:55:11 PID: 0
2020/07/20 17:55:11 GetProperty: No such property '_NET_WM_NAME' on window 7000002.
2020/07/20 17:55:11 Window name:
2020/07/20 17:55:11 Not a Wine process
2020/07/20 17:55:11 invalid pid 0
2020/07/20 17:55:11 open /proc/0/status: no such file or directory
2020/07/20 17:55:11 Checking process - name:  PID: 0 status: Running
2020/07/20 17:55:11 Suspending
```

**To Reproduce**
1. run glxgears
2. Press "Pause" key

**Expected behavior**
It should work

**Software:**
 - nyrna: v1.1, downloaded binary release from GitHub
 - OS: openSUSE Tumbleweed (snapshot 20200716)
 - Destop Environment: i3wm 4.18.1
 - Python version: 3.8.3 (is it relevant?)

**Comment by etam** [comment]
I think it's not an issue with i3wm, but with the foreground application (glxgears in this case). I checked with `xprop`, that other apps like konsole or firefox do have `_NET_WM_PID` property.

**Comment by Merrit** [comment]
I checked both Konsole & Firefox on my machine (KDE) and they both have this property. Seems like an issue specific to i3 unless you are getting the `_NET_WM_PID` property on any of your applications?

I am not familiar with how i3 works, but a quick search suggests windows can be set to 'float' (rather than tile, I presume). Could you try on a floating window to see if it works there?

**Comment by etam** [comment]
As I wrote, firefox and konsole has this property. I also checked with Diablo 2 playing under wine. Everything works fine with them.

The issue I found is that it doesn't work with glxgears.

According to this specification https://specifications.freedesktop.org/wm-spec/1.4/ar01s05.html `_NET_WM_PID` property is optional.

So I'd change my "Expected behavior" from
> It should work

to
> It should handle missing _NET_WM_PID property with a meaningful message for user.

**Comment by etam** [comment]
and making a window floating makes no difference

**Comment by Merrit** [comment]
I see, I misunderstood. Thought you said that Konsole and Firefox did __not__ have the property.

Seeing as only glxgears is having issues, I will indeed update it to handle a fail with a useful debug message. Thanks for the report :)

**Comment by Merrit** [comment]
Improvements made with e7a4db8f4c90666d614a70160cd233c84a03d006 and in the near future will be a notification as well for failures. Thanks again! :)
