### ISSUE TITLE
Add hotkey support?

### ISSUE THREAD

**Issue by bfenty** [Merrit/nyrna#60]
Would it be possible to set this up to suspend the active window with a hotkey press? Binding it to something like alt+f3 would be really useful to suspend a running game, for instance. 

Great program btw, I'm always finding it very useful as-is.

**Comment by Merrit** [comment]
Toggle for active window is already implemented: https://nyrna.merritt.codes/usage#toggle-active-window

Does that work for you, or were you looking for something different?

**Comment by bfenty** [comment]
I’m sorry I missed this. It looks like exactly what I was asking for. Awesome! I’ll test it out and let you know if I have questions.

**Comment by bfenty** [comment]
Ok. I’m running from the appimage. I’m not really familiar with how those work, but I don’t think it has an install folder with that script? Pardon my ignorance. I’m used to apt install lol.

**Comment by Merrit** [comment]
Yeah, the AppImage isn't setup to work with the hotkey. (It could be, if configured to accept a flag...)

For the time being you will need to use the portable version in order to use the hotkey.

**Comment by bfenty** [comment]
Oh I see. Thanks. Appreciate the help. Thank you again for such a great app.

**Comment by bfenty** [comment]
So now, I assigned alt+F3 to the shortcut for the portable app, and it suspends correctly. But I cannot then restore the program. If I click on the icon in the tray, it is frozen. The main application runs perfectly and works to suspend/restore programs without issue.

I did chmod +x both scripts to make them executable but they are otherwise unmodified. If there is a log that you need please let me know and I'll provide.

Thanks!

**Comment by Merrit** [comment]
Checking I am understanding fully, you are:

- Pressing the hotkey to suspend the app (successful)
- Pressing the hotkey again to resume the app (does not resume / nothing happens)

Is that correct?

Did you try.. 

- Opening the Nyrna GUI to see if it indicates the app is suspended / try resuming from there?
- Try with any other app, or one the one?

**Comment by bfenty** [comment]
I tried with 2-3 apps that work correctly when I use the GUI. I will do some more testing so I can give you a better answer. Specifically I tried Discord, Firefox, and Battletech. I set Alt+F3 as the hotkey (I'm using Pop OS). They suspend correctly but do not come back. Just a blank screen. 

I did not test restoring them from the GUI. I'll mess around to get you better information.

**Comment by bfenty** [comment]
Ok, I've tested with several apps and it appears to suspend successfully. Hitting the hotkeys again simply suspends another window. I'm assuming that the intention is to use the GUI to restart an application, then? Clicking on the application in the menu bar shows the application windows but it is completely non-responsive (this is what I was doing before, I now realize this is in error). If I open the GUI I see the application in the list but it has a green dot. Clicking it, however, does restore the app to functioning again.

So my understanding is that the hotkey suspends, but you need to use the GUI to restore? If so, it would be very helpful to have the GUI dot change to orange when the hotkey is used on an application. I'm not sure if that's feasible. It's working for me now that I know how to use it, however. Thanks for clarifying.

**Comment by Merrit** [comment]
Ahh, a case of the electronics gremlins. Reboots scare them...

Well I am glad it is working anyhow! I will leave this open for a couple days in case it is still an issue. :)

**Comment by bfenty** [comment]
It's working flawlessly. Thanks again for making such a great too

**Comment by Merrit** [comment]
Awesome! :grinning: Glad you enjoy my work!
