### ISSUE TITLE
[BUG] This application will not suspend a game I play often on steam - Apex Legends

### ISSUE THREAD

**Issue by EW-WE** [Merrit/nyrna#64]
I get this message when trying to suspend apex legends, Merrit can you help me out or maybe an explanation why I'm getting this message? Thanks.
I'm new to GitHub so this probably doesn't even count as a bug, but it is a issue I can't seem to find out.

https://imgur.com/a/QB4Bqly

This is the portable version.

**Comment by Merrit** [comment]
Hi there, welcome :)

Just FYI, I believe Apex Legends is an online-only game so just be aware that suspending it will almost certainly disconnect you from your session.

That said, if you try running Nyrna as admin and try it again does it make any difference?

**Comment by EW-WE** [comment]
No, I try running Nyrna as an admin but I still get the same message.

**Comment by Merrit** [comment]
I will try and find some hard drive space to download and test it out for you.

**Comment by Merrit** [comment]
From my testing I think this behaviour is because the game uses Easy Anti Cheat. On a hunch I tried loading up Paladins which also uses that, and it had the same issue.

Unfortunately that isn't something that can be fixed. :woman_shrugging:

**Comment by mrrfv** [comment]
For a better user experience, it would be better if Nyrna showed a detailed error message, clarifying that if the game uses anti-cheat software, it might not be suspendible IMO.

**Comment by Merrit** [comment]
> For a better user experience, it would be better if Nyrna showed a detailed error message, clarifying that if the game uses anti-cheat software, it might not be suspendible IMO.

Sounds like a good idea!

I created an issue for this: https://github.com/Merrit/nyrna/issues/77
