### ISSUE TITLE
Nyrna does not work with Hunt: Showdown [Game]

### ISSUE THREAD

**Issue by BlahaMarquisToken** [Merrit/nyrna#65]
Hi!

When trying to use Nyrna with Hunt: Showdown I get this message in return

"There was a problem interacting with HuntGame.exe"

**Comment by Merrit** [comment]
The issue is because the game uses Easy Anti-Cheat, and unfortunately nothing I can do to resolve that on Windows.

**Comment by BlahaMarquisToken** [comment]
I see, thank you for the quick response!
