### ISSUE TITLE
Version conflict

### ISSUE THREAD

**Issue by Radeox** [Merrit/nyrna#72]
I was trying to build the new version for the AUR but got this error during `flutter pub get`:

```bash
Because test >=1.20.0 depends on test_api 0.4.9 and test >=1.19.4 <1.20.0 depends on test_api 0.4.8, test >=1.19.4 requires test_api 0.4.8 or 0.4.9.
And because every version of flutter_test from sdk depends on test_api 0.4.3, flutter_test from sdk is incompatible with test >=1.19.4.
So, because nyrna depends on both flutter_test from sdk and test ^1.19.5, version solving failed.
Running "flutter pub get" in nyrna...                                   
pub get failed (1; So, because nyrna depends on both flutter_test from sdk and test ^1.19.5,
version solving failed.)
```

I was able to compile it correctly changing the version to:

```
-  test: ^1.19.5
+  test: ^1.17.9
```

Maybe I'm missing something here so here we are 😄 Btw I'm on `flutter stable` branch.

**Comment by Merrit** [comment]
Hi @Radeox 👋

Thanks for opening the issue.

The project follows the Flutter `beta` branch. Please try compiling with beta and see if that helps :slightly_smiling_face:

**Comment by Radeox** [comment]
@Merrit can confirm that building with `beta` branch gives no problems. Closing the issue! 👍🏻

**Comment by Merrit** [comment]
Nice! Thanks for the update :)
