### ISSUE TITLE
2 security vendors and 1 sandbox flagged this file as malicious

### ISSUE THREAD

**Issue by MuditJainRepos** [Merrit/nyrna#86]
Hello and Thanks for writing such a good tool. :bow: 
I check for all files i download for viruses by checking it at Https://www.Virustotal.com 
I uploaded the windows .exe file of Nyrna 2.4.1(https://github.com/Merrit/nyrna/releases/download/v2.4.1/Nyrna-Windows-Installer.exe)
It showed 2 security vendors out of 68 and 1 sandbox flagged this file as malicious.
Can you please look into it. :eyes: 
From what i have read, this is a fantastic tool, i just don't want it to be tagged as malicious without your notice/oversight.
Just wanted to let you know. :)

**Comment by Merrit** [comment]
Hi @MuditJainRepos :wave: 

Thanks for opening the issue! I have submitted false positive reports to these companies, and one of them has already gotten back reporting no malware found. Hopefully the other will be as expedient :smiley:

**Comment by Merrit** [comment]
Both vendor reports have now been removed and the results are green. :tada: 

Thanks again for opening the issue! :bowing_woman:
