### ISSUE TITLE
[Feature Request] Ability to Rebind Nyrna Hotkey on Windows

### ISSUE THREAD

**Issue by jjw410** [Merrit/nyrna#88]
Wanted to say first of all great job Kristen, it had been a while since I used Nyrna and I love how nice and simple the Windows UI!

Could really get a lot of use out of being able to rebind the keyboard shortcut as I'm trying to create a Steam controller profile that does everything my keyboard does. I've made awesome progress, the only problem is Steam's controller API doesn't allow use of the Pause key. And using Nyrna with a controller would be great since I find it primarily useful for gaming!

**Comment by Merrit** [comment]
Hi @jjw410 :wave: 

Binding to the Pause/Break key seems to work for me here, have you tries this?:

- Close the Nyrna hotkey listener, make sure nothing else is using pause as a hotkey as well
- In Steam's controller config press `LB` to listen for button:
![image](https://user-images.githubusercontent.com/9575627/175819969-92e46d9f-4439-4bd7-8d45-f492f6923825.png)
- Press `Pause` on your keyboard; now that controller button / chord sends an emulated `Pause` button press to the OS.
![image](https://user-images.githubusercontent.com/9575627/175819993-d905f7f6-4f4d-41c8-920b-cb4a58301cc9.png)
- Start the Nyrna hotkey listener again, the emulated `Pause` key triggered by the controller config should be caught by Nyrna

**Comment by jjw410** [comment]
Thanks for the quick response! I did just try it there but it doesn't seem to work. Usually when a key is registered in the Steam UI it should say next to the button afterwards, and sure enough re-activating the Nyrna shortcut again and trying it with the controller, nothing happened.

Going back into the interface it seem that Steam isn't picking it up because it's not part of the virtualised keyboard they use :/ 

![steam_GNJWoudf46](https://user-images.githubusercontent.com/44265824/175829328-33e441bd-1a9e-40e5-bb44-107a96b276e1.png)
![steam_GuvzJw2qII](https://user-images.githubusercontent.com/44265824/175829368-b9514e73-debb-407b-a0e0-4011c1d6a67b.png)

These screenshots were taken after I registered the shortcut, and as you can see it doesn't look like I've done anything at all!

**Comment by Merrit** [comment]
My binding screen looks the same, blank because that key isn't on their virtual keyboard - though it works fine for me. Might be a Windows-specific problem.

I will look into some options..

In the meantime, you could also try using [AntiMicroX](https://github.com/AntiMicroX/antimicrox/); something like gamepad triggers antimicrox action, which triggers Nyrna. I've tested this setup successfully on Windows previously.

**Comment by jjw410** [comment]
I double-checked just to be sure and it still doesn't seem to be working. It may be because of the keyboard I use. I have a 70% keyboard that doesn't have a dedicated "pause break" key. So to input "pause break" into the Steam controller interface I have to hold "Fn+P" which may be the fault in the system. Either way, it'd be great to customise said key so I could work my way around it if nothing else! 😊 And thank you for the recommendation!

**Comment by Merrit** [comment]
Hit a few snags looking into a customizable hotkey solution, taking longer than I'd like.

While that is pending, did you try AntiMicroX? It's binding window has a graphical representation of the pause key:

![image](https://user-images.githubusercontent.com/9575627/176973938-a58ed48f-080a-4dcd-94e5-5f3d327be899.png)

**Comment by jjw410** [comment]
AntiMicroX did work with the Pause shortcut! But it's not particularly useful for my case as the different layers of control in Steam mean I can control literally my entire computer with a Dualshock 4/Dualsense controller both in and out of games. AntiMicroX would just interfere in that regard so I'll just have to call it a failure for now, unfortunately.

**Comment by Merrit** [comment]
I do the same sort of custom, layered controls on my gamepad using AntiMicroX: https://github.com/AntiMicroX/antimicrox/wiki/Advanced-Slot-Explanation#hold for things like minimizing windows, triggering Nyrna, toggling mute for my TV, etc :)

**Comment by Merrit** [comment]
@jjw410 

I've published a beta build: https://github.com/Merrit/nyrna/releases/tag/2.5.0-beta

Make sure not to run the old hotkey listener, just Nyrna; then you should be able to rebind the hotkey from settings. Let me know if that works for you :)

**Comment by jjw410** [comment]
Omg, this is fantastic! 😄 Thanks so much for your work Kristen! Seems to be working fine so far, and the rebind interface works a treat -- looks very slick too 👍 I'll keep on using, see if I run into any issues ❤️
