### ISSUE TITLE
Tray icon colour

### ISSUE THREAD

**Issue by BlueManCZ** [Merrit/nyrna#9]
I don't know, how is tray icon handled, but I would prefer a white colour to fit my theme. Is this icon hardcoded or it will adapt to icon-theme, when it finds a suitable icon?

![Snímek z 2020-07-26 18-38-42](https://user-images.githubusercontent.com/17854950/88484581-e21b9780-cf6f-11ea-8685-7601aa9e0a44.png)

**#EDIT**
I guess it's hardcoded, right?
https://github.com/Merrit/nyrna/blob/9b735f04b47881b14b6c85dc1562820ebd6d8285/systray.go#L13

**Comment by Merrit** [comment]
It is just a basic, hard-coded icon yes. Threw it together in Krita in about 3 minutes..

**Comment by BlueManCZ** [comment]
Alright. If I find out, how to make it dynamic, I will let you know.

**Comment by Merrit** [comment]
With the new Flutter codebase this should be easily doable to dynamically choose any color the user wishes for the icon and have it changed for them automatically. This has the further benefit of the code base & shipped artifacts only requiring 1 icon.

Target for this feature will be v2.1 :smiley:

**Comment by Merrit** [comment]
Ability to re-color the icon to anything the user wishes added with 85c7da3631b64d41aca8013f2cb825daf6241034

Resolution is waiting on Flutter implementing system tray support: https://github.com/flutter/flutter/issues/81644

**Comment by Merrit** [comment]
I've had a little time to take a look at this..

I think Windows having a system tray icon to monitor for a hotkey makes sense, as Windows doesn't really have a proper native way to set a custom hotkey like this would require.

Linux on the other hand can easily set a native hotkey from the desktop environment's settings (along with a thousand other options..), so I am wondering: is it even valuable to have a system tray on linux, another program running in the background just to monitor for a hotkey when it can easily be done natively without any extra overhead?

**Comment by BlueManCZ** [comment]
I think I understand what you mean. For example, when you consider a [wayland](https://wayland.freedesktop.org/) as a potential option, there is no natural way for applications to register their own hotkeys and you have to use your desktop environment no matter what.

The question is can this be done completely without a daemon-like approach? I mean, would it be enough to have nyrna a start-stop process and you would type in terminal `nyrna`, or `nyrna pause` / `nyrna resume` or bind this to the keyboard shortcut and nyrna would start, pause current window and exit afterwards? Don't you need a running instance to keep id's of paused windows or would you use some other solution like caching into files?

Or do you just mean running nyrna as a daemon, using commands to operate it and dropping only a tray functionality? This would also be possible.

**Comment by Merrit** [comment]
You are exactly right about Wayland, it is still pretty much impossible to do things like a tray or global hotkey..

This has been heavily refactored recently: Essentially how it is set up at the moment is that when you want to use the "toggle active window" feature you simply bind a hotkey that will launch the `toggle_active_window` executable, and this is all that is required from the user - no graphical environment needed, no having to pass any flags or anything like that -- nice and simple for the user.

Internally when this executable launches it will grab the foreground window, minimize & suspend the process, then save the PID & window ID to a file as a cache. On next launch it will see this file, and resume the saved values - then delete the saved values so that the next launch will suspend the foreground window again.

With this new approach it is very fast and seems to be working quite well (much better than before) - though I've only had a chance to test on Windows so far, barring any unforeseen bugs Linux should be good to go as well.

**Comment by BlueManCZ** [comment]
I think it would be nice. Is the "pausing multiple windows" milestone still possible? If I understand it correctly, you solved this with GUI where you select which window to unpause. You would need at least two keyboard bindings:

1. `nyrna pause` to pause active window. This allows you to either pause/unpause one window or pause multiple windows in a row.
2. `nyrna toggle` to choose which window unpause from GUI.
3. (`nyrna unpause`) to unpause windows in some specified order without GUI. Or unpause all at once.

**Comment by Merrit** [comment]
Suspending multiple applications is only set up for the GUI, as if we suspended multiple applications with the hotkey, how would we know which to resume..?

I feel like having a single application at a time work with the toggle hotkey feature is the simplest way to go while still being powerful, and if we need to suspend more than just the active application the GUI is there to manage as many as needed. Did you have a specific desire to be able to suspend & resume multiple applications concurrently with just a hotkey?

**Comment by Merrit** [comment]
Here is a dev build if you'd like to give it a try:

[nyrna-linux-portable.zip](https://github.com/Merrit/nyrna/files/6956915/nyrna-linux-portable.zip)

**Comment by BlueManCZ** [comment]
No, I'm just considering all the options.

When I close the nyrna window, I get an error:

```
../../third_party/dart/runtime/bin/thread_linux.cc: 248: error: pthread error: 16 (Device or resource busy)
[1]    27026 abort      ./nyrna nyrna
```

`./toggle_active_window` works as expected I guess.

**Comment by Merrit** [comment]
> When I close the nyrna window, I get an error

Seems to be an error from the dart sdk, but doesn't appear to be an issue for Nyrna 😄 

Glad to hear it is working on your end! I took a bit of time to test it on Linux as well, to me so far it seems to be fast & effective, and as expected setting up a native hotkey to run the toggle executable was a breeze.
