### ISSUE TITLE
[Feature Request] Reduce working set on windows.

### ISSUE THREAD

**Issue by AndreyRGW** [Merrit/nyrna#91]
It would be nice if on windows you could add a checkbox in the settings that allows you to clear the working set when you suspend the program.

**Comment by Merrit** [comment]
Hi @AndreyRGW :wave: 

Can you clarify what you mean? Especially by the "working set"?

**Comment by AndreyRGW** [comment]
> Hi @AndreyRGW 👋
> 
> Can you clarify what you mean? Especially by the "working set"?

Well, the working set is the virtual memory pages in which the process stores the data it needs. Famous windows programs like process hacker and mem reduct have this function. And it would be great if when you freeze program via nyrna, memory occupied by frozen program would be cleaned.

**Comment by Merrit** [comment]
I see. I looked into it a bit, for example: https://stackoverflow.com/a/5406063/9872288

From what I can tell this isn't terribly effective at.. much of anything. It also _won't_ allow an application / game to free up the RAM it is using, just a small fraction of "reserved" memory. Were you thinking this would allow one to get back the RAM of a suspended process?

**Comment by AndreyRGW** [comment]
[Example video](https://imgur.com/a/Nd6pSl7)

**Comment by Merrit** [comment]
https://superuser.com/a/1009390/560254

As far as I can tell, all this does is move unused memory from RAM to the swap / pagefile. Which the OS will do itself if it is feeling low on RAM (and sufficient pagefile space is available).

So visually you perhaps feel better seeing the "used memory" numbers go down, but practically I don't see how it has any benefit. Perhaps you can enlighten me?

**Comment by AndreyRGW** [comment]
aight then

**Comment by Merrit** [comment]
To be clear, if you feel this has a practical benefit I have missed: _I welcome being corrected!_ :smiley: 

If it is an aesthetic issue, I can see how that would be nice to have - and I'd be happy to consider a pull request that adds such a feature, though I do not have the bandwidth for writing such a feature myself.

I hope that is clear, and not overly pedantic! :rainbow: 

Please feel free to re-open the issue if you change your mind. :sunflower:
