### ISSUE TITLE
[Feature request] Semi-auto refresh.

### ISSUE THREAD

**Issue by i11111000000** [Merrit/nyrna#95]
Hi and thank you again for the useful tool. It would be nice for the app to refresh a sec after hotkey is used. Also on window restore from tray or taskbar.

**Comment by Merrit** [comment]
Sounds pretty reasonable! :+1:

**Comment by Merrit** [comment]
Implemented with [v2.6.0](https://github.com/Merrit/nyrna/releases/tag/v2.6.0).
