### ISSUE TITLE
Not starting automatically with system boot (Win 10, V2.5.2)

### ISSUE THREAD

**Issue by jjw410** [Merrit/nyrna#98]
Oh no, it's me again. The same problem as before, version 2.5.2, everything is enabled to launch on startup but still nothing!

**Comment by Merrit** [comment]
Please check a few things:

- Is the icon in the overflow?

![image](https://user-images.githubusercontent.com/9575627/185949174-1bd3cb29-8fae-4558-822a-7ddaa190ebce.png)

- Does Nyrna show up in task manager?

![image](https://user-images.githubusercontent.com/9575627/185949503-aa8848d9-217c-42ad-8777-5dc6db16369d.png)

- Does the Nyrna startup entry exist in `%AppData%\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`?

**Comment by jjw410** [comment]
The first thing I did was check those and no, they're not there. Just checked the Startup folder and it's in there as well! I'm going to do another RevoUnistaller full wipe reinstall and see if I just had some bad luck.

**Comment by jjw410** [comment]
Ah! There it was, it was there but it was disabled for some reason. Very weird. Disabled that and on restart it launched just fine. Thanks so much for the help! 😄

**Comment by Merrit** [comment]
Excellent! Glad to hear it is working :tada: :grinning:
